# Generated by Django 3.1.5 on 2021-02-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thndr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='price'),
        ),
    ]
