# Generated by Django 3.1.5 on 2021-02-07 00:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thndr', '0002_auto_20210207_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Holding',
        ),
        migrations.AlterModelOptions(
            name='holding',
            options={'verbose_name': 'Holding', 'verbose_name_plural': 'Holdings'},
        ),
    ]
