# Generated by Django 3.1.5 on 2021-02-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thndr', '0003_auto_20210207_0051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('user', 'stock'), name='unique holding'),
        ),
    ]
