# Generated by Django 3.1.5 on 2021-02-07 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thndr', '0004_auto_20210207_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thndr.stock', verbose_name='stock'),
        ),
    ]
